---
name: Autobump (not really)

on:
  # workflow_dispatch:

  repository_dispatch:
    types: [my-event]

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest

    env:
      FORMULA: ${{ github.event.client_payload.formula }}

    steps:

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.HOMEBREW_APP_ID }}
          private-key: ${{ secrets.HOMEBREW_APP_KEY }}
          owner: peter-bread
          repositories: homebrew-tap

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git
        uses: Homebrew/actions/git-user-config@main

      # - name: List all formulae
      #   id: formulae
      #   run: |
      #     FORMULAE="$(find Formula -maxdepth 1 -name '*.rb' -exec basename {} .rb \; | tr '\n' ' ')"
      #     echo "formulae=$FORMULAE" >> "$GITHUB_OUTPUT"
      #
      # - name: Install dependencies
      #   run: |
      #
      #     IFS=" " read -r -a formulae <<<"$FORMULAE"
      #
      #     for f in "${formulae[@]}"; do
      #       brew deps --include-build --include-test "$f"
      #     done
      #       brew install "$(brew deps --include-build --include-test "$f")" || true
      #     done
      #   env:
      #     FORMULAE: ${{ steps.formulae.outputs.formulae }}
      #     HOMEBREW_NO_ENV_HINTS: 1

      - name: Install dependencies for ${{ env.FORMULA }}
        run: |
          brew deps --include-build --include-test "$FORMULA" | xargs brew install
        env:
          HOMEBREW_NO_ENV_HINTS: 1

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        with:
          # Custom GitHub access token with only the 'public_repo' scope enabled
          # token: ${{ secrets.HOMEBREW_TAP_PAT }}
          token: ${{ steps.app-token.outputs.token }}
          fork: false
          formulae: ${{ env.FORMULA }}
          # formulae: ${{ steps.formulae.outputs.formulae }}
